#!/usr/bin/env node
// Generated by purs bundle 0.14.0
var PS = {};
(function(exports) {
  exports.replace = function(options) {
    return function () {
      require('replace-in-file').sync(options)
    }
  }
})(PS["FS"] = PS["FS"] || {});
(function($PS) {
  "use strict";
  $PS["FS"] = $PS["FS"] || {};
  var exports = $PS["FS"];
  var $foreign = $PS["FS"];
  exports["replace"] = $foreign.replace;
})(PS);
(function($PS) {
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var FS = $PS["FS"];                
  var runCommentReplace = FS.replace({
      files: "./src/graphql/query.rs",
      from: "//Replace me",
      to: "//Replaced Bitch"
  });
  var main = runCommentReplace;
  exports["runCommentReplace"] = runCommentReplace;
  exports["main"] = main;
})(PS);
PS["Main"].main();