name:                vhagar
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/rajatsharma/vhagar#readme
license:             BSD3
author:              Rajat Sharma
maintainer:          rajatsharma@github.com
copyright:           2022 Rajat Sharma
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - inflections
  - process
  - soothsayer
  - directory
  - neat-interpolation

executables:
  kensai:
    source-dirs:      src
    main:             Main.hs
